[package]
name = "tezuri-desktop"
version = "0.1.0"
edition = "2021"
description = "Tezuri desktop shell"

[build-dependencies]
tauri-build = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.2"

[dependencies]
tezuri = { path = ".." }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tauri-plugin-dialog = "2.7.2"
