<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Tezuri</RootNamespace>
    <AssemblyName>Tezuri.App</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sylin.Koan.App" />
    <PackageReference Include="Sylin.Koan.Data.Core" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>
</Project>
